-- BOYS OLAP warehouse (Oracle) — the "library" the quant model reads.
-- Star schema for historical football matches: two dimensions + one fact.
-- Runs once on a fresh container (mounted init dir); the Python loader applies
-- the same DDL idempotently against an already-initialized container.
--
-- Scope note: fact_model_prob (NBA 538 probabilities) and fact_price_tick
-- (Polymarket ticker) get their own tables when that data is wired in E2/E5 —
-- we don't create empty tables here (no dead schema).

CREATE TABLE dim_season (
  season_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label     VARCHAR2(16) NOT NULL,
  CONSTRAINT uq_dim_season_label UNIQUE (label)
);

CREATE TABLE dim_team (
  team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    VARCHAR2(128) NOT NULL,
  CONSTRAINT uq_dim_team_name UNIQUE (name)
);

CREATE TABLE fact_match (
  match_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id    NUMBER NOT NULL,
  home_team_id NUMBER NOT NULL,
  away_team_id NUMBER NOT NULL,
  match_date   DATE   NOT NULL,
  result       VARCHAR2(1),          -- 'H' | 'D' | 'A' | NULL
  home_odds    NUMBER,               -- opening decimal odds (closing added in E2-B08)
  draw_odds    NUMBER,
  away_odds    NUMBER,
  CONSTRAINT fk_fm_season FOREIGN KEY (season_id)    REFERENCES dim_season(season_id),
  CONSTRAINT fk_fm_home   FOREIGN KEY (home_team_id) REFERENCES dim_team(team_id),
  CONSTRAINT fk_fm_away   FOREIGN KEY (away_team_id) REFERENCES dim_team(team_id),
  CONSTRAINT uq_fact_match UNIQUE (season_id, match_date, home_team_id, away_team_id),
  CONSTRAINT ck_fm_result  CHECK (result IN ('H', 'D', 'A'))
);

CREATE INDEX ix_fm_season ON fact_match(season_id);
CREATE INDEX ix_fm_date   ON fact_match(match_date);
